// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr-10h6c8S7QOTPiev16rKe3uOz5X2q90',
    appId: '1:631270274081:web:e55b995999590eac8b9f60',
    messagingSenderId: '631270274081',
    projectId: 'smart-home-47a2c',
    authDomain: 'smart-home-47a2c.firebaseapp.com',
    storageBucket: 'smart-home-47a2c.firebasestorage.app',
    measurementId: 'G-ERG2Y43CVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8a82K0mjHdvTKK-usu9TDjoYSwehNvzc',
    appId: '1:631270274081:android:13ea7d30e1c438f78b9f60',
    messagingSenderId: '631270274081',
    projectId: 'smart-home-47a2c',
    storageBucket: 'smart-home-47a2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVuaso20W1_iklAhPDf0Haj52SjGLXDP4',
    appId: '1:631270274081:ios:09ded21f5855d0b38b9f60',
    messagingSenderId: '631270274081',
    projectId: 'smart-home-47a2c',
    storageBucket: 'smart-home-47a2c.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVuaso20W1_iklAhPDf0Haj52SjGLXDP4',
    appId: '1:631270274081:ios:09ded21f5855d0b38b9f60',
    messagingSenderId: '631270274081',
    projectId: 'smart-home-47a2c',
    storageBucket: 'smart-home-47a2c.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr-10h6c8S7QOTPiev16rKe3uOz5X2q90',
    appId: '1:631270274081:web:cb2216a8d3e9bd398b9f60',
    messagingSenderId: '631270274081',
    projectId: 'smart-home-47a2c',
    authDomain: 'smart-home-47a2c.firebaseapp.com',
    storageBucket: 'smart-home-47a2c.firebasestorage.app',
    measurementId: 'G-G0R0WLJPNT',
  );

}